#### 1. Arrays

In [2]:
import numpy

def arrays(arr):
    # complete this function
    # use numpy.array
    return numpy.array(arr[::-1], float)
arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 34 -10
[-10.  34.   2.   1.]


#### 2. Shape and Reshape

In [3]:
import numpy as np
print (np.array(list(map(int,input().split()))).reshape(3,3))

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### 3. Transpose an Flatten

In [4]:
import numpy as np
n, m = map(int, input().split())
a = np.array([input().split() for i in range(n)], int)
print (a.transpose())
print (a.flatten())

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


#### 4. Concatenate

In [5]:
import numpy as np
n, m, p = map(int, input().split())
a = np.array([input().split() for i in range(n)], int).reshape(n, p)
b = np.array([input().split() for i in range(m)], int).reshape(m, p)
print(np.concatenate((a, b),axis=0))

4 3 2 
1 2 
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


#### 5. Zeroes and ones

In [6]:
import numpy as np
a = list(map(int, input().split()))
print (np.zeros(a, dtype = np.int))
print (np.ones(a, dtype = np.int))

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


#### 6. Eye and identity

In [7]:
import numpy as np
np.set_printoptions(legacy='1.13')
a, b = list(map(int, input().split()))
print (np.eye(a, b))

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


#### 7. Array mathematics

In [9]:
import numpy as np
n, m = list(map(int, input().split()))
A = np.array([list(map(int, input().split())) for i in range(n)], int)
B = np.array([list(map(int, input().split())) for i in range(n)], int)
print(np.add(A,B))
print(np.subtract(A,B))
print(np.multiply(A,B,))
print(np.floor_divide(A,B))
print(np.mod(A,B))
print(np.power(A,B))


1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


#### 8. Floor, ceil, rint

In [10]:
import numpy as np
np.set_printoptions(legacy='1.13')
a = np.array(input().split(),float)
print(np.floor(a))
print(np.ceil(a))
print(np.rint(a))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


#### 9. Sum and prod

In [11]:
import numpy as np 
n,m = map(int,input().split())
a = np.array([input().split() for i in range(n)], int)
print(np.prod((np.sum(a,axis=0))))

2 2
1 2
3 4
24


#### 10. Min and Max

In [13]:
import numpy as np
n, m = map(int, input().split())
a = np.array([list(map(int,(input().split()))) for i in range(int(n))])
print(np.max(np.min(a, axis = 1)))

4 2
2 5
3 7
1 3
4 0
3


#### 11. Mean, Var, Std

In [14]:
import numpy as np
N, M = map(int, input().strip().split())
a = np.array([ input().strip().split() for _ in range(N) ], int)
print(np.mean(a, axis = 1))
print(np.var(a, axis = 0))
print(round(np.std(a, axis = None),11))

2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


#### 12. Dot and Cross

In [15]:
import numpy as np
a =int(input())
b =np.array([list(map(int,input().split())) for i in range(a)])
c =np.array([list(map(int,input().split())) for i in range(a)])
print(np.dot(b, c))

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


#### 12. inner and outer

In [16]:
import numpy as np
a = np.array(input().split(), int)
b = np.array(input().split(), int)
print(np.inner(a, b))
print(np.outer(a, b))

0 1
2 3
3
[[0 0]
 [2 3]]


#### 13. Polynomils

In [18]:
import numpy  as np
n = list(map(float,input().split()));
m = input();
print(np.polyval(n,int(m)));

1.1 2 3
0
3.0


#### 14. Linear Algrebra

In [19]:
import numpy as np
np.set_printoptions(legacy='1.13')
n = int(input())
a = np.array([input().split() for i in range(n)],float)
print(np.linalg.det(a))

2
1.1 1.1
1.1 1.1
0.0
